### ISSUE TITLE
Mod crash

### ISSUE THREAD

**Issue by Chancho91** [asanetargoss/metamorph#13]
When I hit a mob, the game crashes. Here is the crash report.
[crash-2020-03-07_12.00.25-client.txt](https://github.com/asanetargoss/Changeling/files/4302191/crash-2020-03-07_12.00.25-client.txt)

**Comment by asanetargoss** [comment]
Hmmmm

**Comment by asanetargoss** [comment]
Does the crash still occur when Changeling is not loaded?

**Comment by asanetargoss** [comment]
Is this crash still occurring for you?

**Comment by asanetargoss** [comment]
This seems like a serious crash, but I don't have the time to install/remove a bunch of mods to track down the cause. If someone else encounters this crash and is able to narrow down the mods responsible (and confirm Changeling is required to reproduce the bug) then I can look into this more.
