### ISSUE TITLE
Hostile Bat

### ISSUE THREAD

**Issue by BabyGrootTheEpic** [asanetargoss/metamorph#16]
The default morph config gives the bat the hostile ability in the newest version (1.2-1.12.2_command-fixes). This could be intentional but I assume it isn't because of how ovepowered it makes the bat.
https://github.com/asanetargoss/Changeling/blob/changeling-master/src/main/resources/assets/metamorph/morphs.json

**Comment by asanetargoss** [comment]
It's intentional.
