### ISSUE TITLE
POV Doesn't work

### ISSUE THREAD

**Issue by Mugiwaxar** [asanetargoss/metamorph#17]
Hello
Same issue than here: https://github.com/mchorse/metamorph/issues/207

POV doesn't work

Version: changeling-1.2-1.12.2

**Comment by asanetargoss** [comment]
It's possible MPM's config option doesn't fully disable POV, and MPM is still overriding POV to be the default. Try disabling MPM.

**Comment by Mugiwaxar** [comment]
It work without MPM

**Comment by asanetargoss** [comment]
Okay, then it's on MPM's end. Nothing I can do.
