### ISSUE TITLE
Inconsistency with Snow Golem morphs and their snowball throw

### ISSUE THREAD

**Issue by James103** [asanetargoss/metamorph#22]
Minecraft 1.12.2
Forge 14.23.5.2854
DominionLib 1.0.4
Changeling 1.2

There is an inconsistency with Snow Golem morphs and their snowball throw. Basically, the snow golem morph's snowball throw has about twice the power compared to a normal player. Additionally, the snow golem morph's snowball throw does not use up the snowballs in your inventory, whereas right-clicking a snowball to throw it does consume the snowball.

To fix the throwing power, either a) the snow golem morph's snowball throw should be reduced in power to match with a normal player or b) when the morphed player uses (right clicks) a snowball to throw it, the throwing power should be increased to match.

To fix the resource usage, either a) the snow golem morph's snowball throw should consume snowballs in your inventory if you have any or b) when the morphed player uses (rights) a snowball to throw it, the snowball should not be consumed.

**Comment by asanetargoss** [comment]
Ideally, morph gameplay should match the behavior of the mob, not the player. The exception being when it makes gameplay extremely unfun or buggy. For example: the squid mob can only swim for short distances, and can't move on land. This would not be fun for the player to experience in a vanilla gameplay context.

It sounds to me like the default behavior of the Snow Golem more closely matches the mob, and does not make the gameplay extremely unfun or buggy, so the default behavior is fine.
