### ISSUE TITLE
[Suggestion] Lightning affects morphed players

### ISSUE THREAD

**Issue by James103** [asanetargoss/metamorph#24]
In vanilla Minecraft, some mobs turn into others when struck by lightning. I would like if there was an option that if turned on, would make lightning affect morphed players just like it affects normal mobs. 

By default, Pig morphs remorph into Zombie Pigman, Villager morphs remorph into Witches, and Creeper morphs become charged, though this can be changed in the config files.

Note that currently none of this is implemented.

**Comment by asanetargoss** [comment]
On second thought, in light of https://github.com/asanetargoss/Changeling/issues/25 , I think this falls in the same category of working better with features that Changeling does not have, and aside from that being too obscure and not useful enough.
