### ISSUE TITLE
[Suggestion] New ability for Zombie Villager: Can be cured

### ISSUE THREAD

**Issue by James103** [asanetargoss/metamorph#25]
In vanilla Minecraft, Zombie Villagers can be cured. I would like it if that was an ability that applied to Zombie Villager morphs. Basically, by eating a golden apple while under the Weakness effect, you get the Strength effect for 2-5 minutes, after which you morph into a normal Villager.

**Comment by asanetargoss** [comment]
For this feature to even make sense from a gameplay perspective, you would have to be prevented from morphing. This is currently not possible in Changeling. Even then, it's an extremely obscure mechanic, and I can't see myself implementing this.
