### ISSUE TITLE
Undead morphs aren't healed by Instant Damage and vice versa.

### ISSUE THREAD

**Issue by James103** [asanetargoss/metamorph#35]
Minecraft 1.12.2
Forge 14.23.5.2854
DominionLib 1.0.4
Changeling 1.2

Expected behavior: When morphed as an undead, Instant Health damages you and Instant Damage heals you, similar to actual undead.

Actual behavior: When morphed as an undead, Instant Health heals you and Instant Damage damages you, unlike actual undead.

**Comment by asanetargoss** [comment]
The next version of Changeling will add this.
