### ISSUE TITLE
Suggetion for Changeling mod

### ISSUE THREAD

**Issue by Taknax** [asanetargoss/metamorph#39]
I love Metamorph, but as i saw their is a gameplay oriented project i was really happy.

I have just one suggestion for this amazing idea.

A Morphbook (or electronic device, but i would love a book :)) to make it really survival. You need the book in the inventory, or you have to unlock the ability to morph, also you can decide yourself you wanna be a shapeshifter. The GUI could be more compacter. Maybe in in book pages. Per morph a page? The book should be upgradable and the result should be cooldownreduction. Cooldownreduction should be configurable for modpacker.

I hope you gonna continue with this nice work. I think this have very much potential and is a nice idea.

**Comment by asanetargoss** [comment]
Hey, thanks for the suggestion. While Changeling is gameplay-oriented, balance and progression are outside of scope and the intent is that add-ons provide this functionality.

**Comment by Taknax** [comment]
Ok. Lovely work.
