### ISSUE TITLE
Crash w/ Tektopia

### ISSUE THREAD

**Issue by WenXin20** [asanetargoss/metamorph#4]
Minecraft v1.12.2
Forge v14.23.5.2838
Changeling v1.1.8
[Tektopia](https://www.curseforge.com/minecraft/mc-mods/tektopia) v1.1.0

I received this crash after killing a villager from Tektopia. This crash also occurs when picking up the morph from the entity.
[Crash Report](https://paste.dimdev.org/alixumihiw.mccrash)

**Comment by asanetargoss** [comment]
Closing as fixed. A version with the bug fix is currently available on the [releases](https://github.com/asanetargoss/Changeling/releases) page
