### ISSUE TITLE
"mob" attack and some health thingy

### ISSUE THREAD

**Issue by UngaBunga42069** [asanetargoss/metamorph#42]
What does the mob attack do? I always assumed it was the the unarmed damage that a mob could do. Like an iron golem being able to punch way harder than a normal player could. It seems like the Iron Golem is the only mob that is able to hit as hard as they normally would, every other mob/morph hits like a normal player. Anyway to fix this? Also, having the default health of a mob already set would be nice, instead of always having it to 20.

**Comment by asanetargoss** [comment]
Please consult the wiki for how configuration works:

https://github.com/asanetargoss/Changeling/wiki

Health should be calculated automatically for morphs not included in the morphs.json using the base health of the entity. If that is not the case then it may be a bug.

**Comment by UngaBunga42069** [comment]
Yup, every morph has their health set to 20

https://imgur.com/a/VlGskoy < Metamorph, Has normal health of mob

https://imgur.com/a/3txJc5c < Changeling, Has health always set to 20, this affects every mob

also the "mob" attack is not even mentioned in the wiki, yet is still a thing in-game, wonder what it does...

**Comment by asanetargoss** [comment]
That is the morph builder menu. Changeling is survival-focused, so if something breaks in that menu, I'm not particularly concerned about it. If you acquire a morph in survival, i.e. by killing a mob, then morph using the survival morph menu, you should see your health on your HUD bar change to equal the health of the mob. That is a feature I would be more concerned of if it was broken.

Meaning of attacks can be discovered from the wiki. Please try looking again.

**Comment by UngaBunga42069** [comment]
https://imgur.com/a/yH79moN

**Comment by asanetargoss** [comment]
Oh you mean that particular attack, not attacks in general.

In that case, I don't know, lol.
