### ISSUE TITLE
Incompatibility with modularmovements mod

### ISSUE THREAD

**Issue by xkforce** [asanetargoss/metamorph#49]
When changeling is installed alongside modularmovements, crouching results in visual "vibration" as if the mods are fighting one another for control over the camera. Crouching itself properly modifies the player's hitbox etc. correctly it's just a visual glitch. This issue does not appear to be version specific ie all tested mod version combinations had the glitch

**Comment by asanetargoss** [comment]
https://github.com/asanetargoss/Changeling/wiki/F.A.Q.#my-screen-goes-up-and-down

**Comment by asanetargoss** [comment]
^ Let me know if this doesn't fix your problem
