### ISSUE TITLE
Oxygen bar visually screwing up in multiplayer

### ISSUE THREAD

**Issue by DrBlocks** [asanetargoss/metamorph#5]
Hi !

I'm using changeling on a 1.12.2 server, it works pretty fine but there's a bug with the air-bubble gauge when you morph into a squid (i guess this extends to all water breathing mobs ?) : once you've used said morph, the gauge is not actualized any more when in player form, hence making you unable to know how much air you've got left (but you can still drown even if it looks like you're breathing under water !).

I've tried reproducing this in different configurations, and it seems this only happens when playing on a server.

How to reproduce (connected to a dedicated server) :
------------------------------------
- be a player
- morph into a mob that has ability to breathe under water
- take a dip
- morph back into a player
- looks like you're not drowning... just wait
- there you go !
- O² bar screwed up

Screenshot link (out of water, oxygen bar stuck, not replenishing) : https://i.imgur.com/K1F48d7.png

**Comment by asanetargoss** [comment]
This turned out to not be a cross-mod compatibility bug and was indeed a server-specific bug. A version with the fix is currently available on the [releases](https://github.com/asanetargoss/Changeling/releases) page.
