### ISSUE TITLE
Bat or Morph Atrifacts 

### ISSUE THREAD

**Issue by SirMAL1CE** [asanetargoss/metamorph#8]
We have been struggling with specifically Bat(mob) artifacts spawning in our world. This Only begins once you have acquired the bat morph by killing a bat. The artifact is a Bat but it sits in one place until you walk past. Then it attaches to you head and kills you. When attached to your head you cannot interact with any objects or Environment and you cannot kill the bat. The only way we have found to clean up the server or local game is to create a 2 block cutout, attach the bat, run into the 2 block high spot and exit the world. When you re-enter the world the bat does not seem to be able to spawn because the space above your head is blocked. This is what we have been doing the past year to keep the mod in in our mod pack but would like to find out if it is a fixable issue? Thanks for all the time and energy you put into the mod and I hope this is helpful.

**Comment by asanetargoss** [comment]
Changeling only adds one entity to the game. It's a floating version of a mob that drops when you kill the mob. Also it's usually cyan and transparent. The only thing it does is grant you the morph of the mob when you pick it up. Changeling does not do anything on its own to prevent the player from interacting with the environment.

However, if you are morphed into a bat, and either 1) Another mod has changed vanilla bat behavior, or 2) The bat you are morphed as is not a vanilla bat, there is a chance something like this could happen.

In either case, I recommend trying to see if you can reproduce this with Changeling by itself, and if not, using process of elimination to repeatedly cut the list of mods potentially responsible for the bug in half until you figured out which mods caused it.

What would also be helpful is if you post a link to a pastebin containing your latest log file after you've reproduced the bug. And it would also be helpful if you posted the name and mod version of any mods needed to reproduce the bug and the Minecraft version you are using.

**Comment by asanetargoss** [comment]
With the current information, I don't know what caused this bug. It could be Changeling or it could be some entirely different mod. Please let me know if you are able to provide more information, particularly of the kind I have asked for above.
